package com.cardprice.app.data.collection

/**
 * Links to PokeCottage's own pages for each set (card list and master-set guide).
 * PokeCottage's terms don't allow copying its content, so the app only links out.
 * Generated by matching TCGdex English set names against pokecottage.com/sitemap.xml.
 */
data class PokeCottageLinks(val cardList: String?, val masterSetGuide: String?)

object PokeCottage {
    const val LIBRARY = "https://pokecottage.com/card-list-library"
    const val CHINESE_LIBRARY = "https://pokecottage.com/card-list-library?filter=chinese"

    private val links: Map<String, PokeCottageLinks> = mapOf(
        "sm1" to PokeCottageLinks("https://pokecottage.com/sets/sun-moon-card-list", null),
        "sm2" to PokeCottageLinks("https://pokecottage.com/sets/guardians-rising-card-list", null),
        "sm3" to PokeCottageLinks("https://pokecottage.com/sets/burning-shadows-card-list", null),
        "sm3.5" to PokeCottageLinks("https://pokecottage.com/sets/shining-legends-card-list", null),
        "sm4" to PokeCottageLinks("https://pokecottage.com/sets/crimson-invasion-card-list", null),
        "sm5" to PokeCottageLinks("https://pokecottage.com/sets/ultra-prism-card-list", null),
        "sm6" to PokeCottageLinks("https://pokecottage.com/sets/forbidden-light-card-list", null),
        "sm7" to PokeCottageLinks("https://pokecottage.com/sets/celestial-storm-card-list", null),
        "sm7.5" to PokeCottageLinks("https://pokecottage.com/sets/dragon-majesty-card-list", null),
        "sm8" to PokeCottageLinks("https://pokecottage.com/sets/lost-thunder-card-list", null),
        "sm9" to PokeCottageLinks("https://pokecottage.com/sets/team-up-card-list", null),
        "det1" to PokeCottageLinks("https://pokecottage.com/sets/detective-pikachu-card-list", null),
        "sm10" to PokeCottageLinks("https://pokecottage.com/sets/unbroken-bonds-card-list", null),
        "sm11" to PokeCottageLinks("https://pokecottage.com/sets/unified-minds-card-list", null),
        "sm115" to PokeCottageLinks("https://pokecottage.com/sets/hidden-fates-card-list", null),
        "sm12" to PokeCottageLinks("https://pokecottage.com/sets/cosmic-eclipse-card-list", null),
        "swsh1" to PokeCottageLinks("https://pokecottage.com/sets/sword-shield-card-list", null),
        "swsh2" to PokeCottageLinks("https://pokecottage.com/sets/rebel-clash-card-list", null),
        "swsh3" to PokeCottageLinks("https://pokecottage.com/sets/darkness-ablaze-card-list", null),
        "swsh3.5" to PokeCottageLinks("https://pokecottage.com/sets/champions-path-card-list", null),
        "swsh4" to PokeCottageLinks("https://pokecottage.com/sets/vivid-voltage-card-list", null),
        "swsh4.5" to PokeCottageLinks("https://pokecottage.com/sets/shining-fates-card-list", null),
        "swsh5" to PokeCottageLinks("https://pokecottage.com/sets/battle-styles-card-list", null),
        "swsh6" to PokeCottageLinks("https://pokecottage.com/sets/chilling-reign-card-list", null),
        "swsh7" to PokeCottageLinks("https://pokecottage.com/sets/evolving-skies-card-list", null),
        "cel25" to PokeCottageLinks("https://pokecottage.com/sets/celebrations-card-list", null),
        "swsh8" to PokeCottageLinks("https://pokecottage.com/sets/fusion-strike-card-list", null),
        "swsh9" to PokeCottageLinks("https://pokecottage.com/sets/brilliant-stars-card-list", null),
        "swsh10" to PokeCottageLinks("https://pokecottage.com/sets/astral-radiance-card-list", null),
        "swsh10.5" to PokeCottageLinks("https://pokecottage.com/sets/pokemon-go-card-list", null),
        "swsh11" to PokeCottageLinks("https://pokecottage.com/sets/lost-origin-card-list", null),
        "swsh12" to PokeCottageLinks("https://pokecottage.com/sets/silver-tempest-card-list", null),
        "swsh12.5" to PokeCottageLinks("https://pokecottage.com/sets/crown-zenith-card-list", "https://pokecottage.com/crown-zenith-master-set-guide"),
        "sv01" to PokeCottageLinks("https://pokecottage.com/sets/scarlet-violet-card-list", "https://pokecottage.com/scarlet-violet-master-set-guide"),
        "sv02" to PokeCottageLinks("https://pokecottage.com/sets/paldea-evolved-card-list", "https://pokecottage.com/paldea-evolved-master-set-guide"),
        "sv03" to PokeCottageLinks("https://pokecottage.com/sets/obsidian-flames-card-list", "https://pokecottage.com/obsidian-flames-master-set-guide"),
        "sv03.5" to PokeCottageLinks("https://pokecottage.com/sets/151-card-list", "https://pokecottage.com/151-master-set-guide"),
        "sv04" to PokeCottageLinks("https://pokecottage.com/sets/paradox-rift-card-list", "https://pokecottage.com/paradox-rift-master-set-guide"),
        "sv04.5" to PokeCottageLinks("https://pokecottage.com/sets/paldean-fates-card-list", "https://pokecottage.com/paldean-fates-master-set-guide"),
        "sv05" to PokeCottageLinks("https://pokecottage.com/sets/temporal-forces-card-list", "https://pokecottage.com/temporal-forces-master-set-guide"),
        "sv06" to PokeCottageLinks("https://pokecottage.com/sets/twilight-masquerade-card-list", "https://pokecottage.com/twilight-masquerade-master-set-guide"),
        "sv06.5" to PokeCottageLinks("https://pokecottage.com/sets/shrouded-fable-card-list", "https://pokecottage.com/shrouded-fable-master-set-guide"),
        "sv07" to PokeCottageLinks("https://pokecottage.com/sets/stellar-crown-card-list", "https://pokecottage.com/stellar-crown-master-set-guide"),
        "sv08" to PokeCottageLinks("https://pokecottage.com/sets/surging-sparks-card-list", "https://pokecottage.com/surging-sparks-master-set-guide"),
        "sv08.5" to PokeCottageLinks("https://pokecottage.com/sets/prismatic-evolutions-card-list", "https://pokecottage.com/prismatic-evolutions-master-set-guide"),
        "sv09" to PokeCottageLinks("https://pokecottage.com/sets/journey-together-card-list", "https://pokecottage.com/journey-together-master-set-guide"),
        "sv10" to PokeCottageLinks("https://pokecottage.com/sets/destined-rivals-card-list", "https://pokecottage.com/destined-rivals-master-set-guide"),
        "sv10.5b" to PokeCottageLinks("https://pokecottage.com/sets/black-bolt-card-list", "https://pokecottage.com/black-bolt-master-set-guide"),
        "sv10.5w" to PokeCottageLinks("https://pokecottage.com/sets/white-flare-card-list", "https://pokecottage.com/white-flare-master-set-guide"),
        "me01" to PokeCottageLinks("https://pokecottage.com/sets/mega-evolution-card-list", "https://pokecottage.com/mega-evolution-master-set-guide"),
        "me02" to PokeCottageLinks("https://pokecottage.com/sets/phantasmal-flames-card-list", "https://pokecottage.com/phantasmal-flames-master-set-guide"),
        "me02.5" to PokeCottageLinks("https://pokecottage.com/sets/ascended-heroes-card-list", "https://pokecottage.com/ascended-heroes-master-set-guide"),
        "me03" to PokeCottageLinks("https://pokecottage.com/sets/perfect-order-card-list", "https://pokecottage.com/perfect-order-master-set-guide"),
        "me04" to PokeCottageLinks("https://pokecottage.com/sets/chaos-rising-card-list", "https://pokecottage.com/chaos-rising-master-set-guide"),
        "me05" to PokeCottageLinks("https://pokecottage.com/sets/pitch-black-card-list", "https://pokecottage.com/pitch-black-master-set-guide"),
        "30th" to PokeCottageLinks("https://pokecottage.com/sets/30th-anniversary-card-list", "https://pokecottage.com/30th-celebration-master-set-guide"),
    )

    fun forSet(setId: String): PokeCottageLinks? = links[setId]
}
